name: Test Flow


on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create a release draft for a milestone
        id: create-release-draft
        uses: ./
        with:
          repo-token: ${{ secrets.GTIHUB_TOKEN }}

      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
